# shared/constants.py
"""
Hằng số dùng chung cho cả client và server
"""

# Network
HOST = 'localhost'
PORT = 5555
BUFFER_SIZE = 4096

# Screen
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GRAY = (128, 128, 128)

# Paddle
PADDLE_WIDTH = 15
PADDLE_HEIGHT = 100
PADDLE_SPEED = 8
PADDLE_OFFSET = 20

# Ball
BALL_SIZE = 15
BALL_SPEED_X = 5
BALL_SPEED_Y = 5
BALL_MAX_SPEED = 10
BALL_SPEED_INCREMENT = 0.5  # Tăng thêm mỗi 10s
BALL_SPEED_INTERVAL = 10  # Tăng tốc mỗi 10 giây
# Game
WINNING_SCORE = 5
NET_WIDTH = 5
FONT_SIZE = 48
SMALL_FONT_SIZE = 24

# Message Types
MSG_CONNECT = "CONNECT"
MSG_READY = "READY"
MSG_GAME_STATE = "GAME_STATE"
MSG_INPUT = "INPUT"
MSG_DISCONNECT = "DISCONNECT"
MSG_GAME_OVER = "GAME_OVER"
MSG_WAIT = "WAIT"
MSG_PLAYER_ID = "PLAYER_ID"
MSG_PLAY_AGAIN = "PLAY_AGAIN"
MSG_RESTART = "RESTART"
MSG_AI_MODE = "AI_MODE"

# AI Settings
AI_REACTION_DELAY = 0.05  # Delay để AI không quá hoàn hảo
AI_DIFFICULTY_EASY = 0.6
AI_DIFFICULTY_MEDIUM = 0.8
AI_DIFFICULTY_HARD = 0.95